on:
  - pull_request
  - push

name: ci-cubrid

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      EXTENSIONS: pdo, 'xdebug'
      XDEBUG_MODE: coverage

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]

    services:
      cubrid:
        image: cubrid/cubrid:11.3
        ports:
          - 33000:33000
          - 8001:8001
        options: --name=cubrid --privileged
        env:
          CUBRID_DB: demodb
          CUBRID_USER: dba
          CUBRID_PASSWORD: ""

    steps:
      - name: Checkout.
        uses: actions/checkout@v5

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          php-version: ${{ matrix.php }}
          tools: pecl

      - name: Verify CUBRID extension (backup compilation if needed)
        run: |
          echo "Checking for CUBRID extensions..."
          php -m | grep -i cubrid || echo "No CUBRID extensions found"

          if ! php -r "print_r(PDO::getAvailableDrivers());" | grep -q "cubrid"; then
            echo "PDO_CUBRID not found, compiling from official source..."

            source $GITHUB_ENV

            git clone https://github.com/CUBRID/cubrid-pdo.git
            cd cubrid-pdo
            phpize
            ./configure --with-pdo-cubrid=/opt/CUBRID
            make && sudo make install

            echo "extension=pdo_cubrid.so" | sudo tee -a $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||")
          fi

          echo "Available PDO drivers:"
          php -r "print_r(PDO::getAvailableDrivers());"

      - name: Update composer.
        run: composer self-update

      - name: Install dependencies with composer.
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run CUBRID tests with PHPUnit.
        run: vendor/bin/phpunit --group cubrid --coverage-clover=coverage.xml --colors=always

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
